apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: a424iho32-python
  janus-idp.io/tekton: a424iho32-python
  backstage.io/kubernetes-id: a424iho32-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: a424iho32-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
