apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: a424iho32-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-c5ddfdd23d.m96z.p3.openshiftapps.com/rhtap/rhtap-qe:15169bb32f2694bb3e9ab43970a7e48755dba31a@sha256:6f6904c834972b8a51a97a79c5605dec5a420efa757cf1a97d8732ae7aca5aab
          name: container-image
